# Copyright (c) 2019-2020-2021-2022 Luca Cappa
# Released under the term specified in file LICENSE.txt
# SPDX short identifier: MIT
#
# The peculiarity of this workflow is that assumes vcpkg stored as a submodule of this repository.
# This workflow does the following:
# - Restores vcpkg artifacts from cache.
# - Sets up vcpkg if needed, then run CMake with CMakePreset.json using a configuration
#   that leverages the vcpkg's toolchain file. This will automatically run vcpkg to install dependencies
#   described by the vcpkg.json manifest file. It will be a no-op if those are restored from cache.
# - Finally builds the sources with Ninja.
env:
  # Path to the CMake build directory.
  build: '${{ github.workspace }}'
  config: 'ninja-release-vcpkg'
  VCPKG_DEFAULT_TRIPLET: x64-windows
name: Build_Win
on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/workflows/lukka_ci_mac.yml
      - .github/workflows/lukka_ci_mac_arm.yml
      - .github/workflows/lukka_ci_win.yml
      - '**/BenchmarkResults/**'
      - '**/FunctionTests/**'
      - '**/**.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - .github/workflows/lukka_ci_mac.yml
      - .github/workflows/lukka_ci_mac_arm.yml
      - .github/workflows/lukka_ci_win.yml
      - '**/BenchmarkResults/**'
      - '**/FunctionTests/**'
      - '**/**.md'
  workflow_dispatch:

jobs:
  job:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
      #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [windows-latest]
    steps:
      - name: Show disk space
        run: Get-PSDrive

      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup sccache action
        uses: mozilla-actions/sccache-action@v0.0.5

      - uses: lukka/get-cmake@latest
      - name: dir
        run: find $RUNNER_WORKSPACE
        shell: bash

      - name: Restore artifacts, or setup vcpkg for building artifacts
        uses: lukka/run-vcpkg@v11.5
        id: runvcpkg
        with:
          # This one is not needed, as it is the default value anyway.
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgJsonGlob: '**/vcpkg.json'

      - name: List $RUNNER_WORKSPACE before build
        run: find $RUNNER_WORKSPACE
        shell: bash

      - name: Prints output of run-vcpkg's (ninja-release-vcpkg) action.
        run: echo "root='${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT }}', triplet='${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_DEFAULT_TRIPLET_OUT }}' "

      - name: Run CMake+vcpkg+Ninja
        uses: lukka/run-cmake@v10.7
        env:
          SCCACHE_GHA_ENABLED: "true"
        id: runcmake
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          configurePreset: 'ninja-release-vcpkg'
          buildPreset: 'ninja-release-vcpkg'

#      - name: Run MSVC Code Analysis
#        uses: microsoft/msvc-code-analysis-action@v0.1.1
#        # Provide a unique ID to access the sarif output path
#        id: run-analysis
#        with:
#          cmakeBuildDirectory: ${{ env.build }}
#          buildConfiguration: ${{ env.config }}
#          # Ruleset file that will determine what checks will be run
#          ruleset: NativeRecommendedRules.ruleset
#          # Paths to ignore analysis of CMake targets and includes
#          # ignoredPaths: ${{ github.workspace }}/dependencies;${{ github.workspace }}/test
#
#        # Upload SARIF file to GitHub Code Scanning Alerts
#      - name: Upload SARIF to GitHub
#        uses: github/codeql-action/upload-sarif@v2
#        with:
#          sarif_file: ${{ steps.run-analysis.outputs.sarif }}
#
#      # Upload SARIF file as an Artifact to download and view
#      - name: Upload SARIF as an Artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: sarif-file
#          path: ${{ steps.run-analysis.outputs.sarif }}

      - name: List $RUNNER_WORKSPACE after build
        run: find $RUNNER_WORKSPACE
        shell: bash

      - name: Run sccache stat for check
        shell: bash
        run: ${SCCACHE_PATH} --show-stats

